### ISSUE TITLE
Request to join ModernAppsNinja

### ISSUE THREAD

**Issue by limecheng** [ModernAppsNinja/Projects#64]
Hi. I'm a VMW employee, MAPBU, SEAK and just watched the Tanzu live earlier on.

My email address is lcheng2 [at] vmware [dot] com. 

**You must enter the secret passphrase where indicated below for this request to be considered**

Secret Passphrase: I am Not a Robot

**Comment by afewell** [comment]
@limecheng  I am so sorry for the delay, I thought I had these requests in a different spot and so I missed this, entirely my mistake. I just added you to the org, you should receive an invite in the email associated with your github account. 

thanks!
